version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: twig-ast-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: twig-ast-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm test
      - store_artifacts:
          path: coverage

